from __future__ import annotations

from pythonore.payoff_ir.black_scholes import BlackScholesMonteCarloModel, build_equity_ore_black_scholes_model
from pythonore.payoff_ir.diff import diff_modules, render_module
from pythonore.payoff_ir.emit_ore import emit_ore_script
from pythonore.payoff_ir.ir import (
    AbsExpr,
    AboveProbExpr,
    AssignStateStmt,
    BelowProbExpr,
    BinaryExpr,
    BooleanExpr,
    CashflowValueExpr,
    CompareExpr,
    ConstantExpr,
    ContinuationValueExpr,
    DiscountFactorExpr,
    EmitCashflowStmt,
    EmitLoggedCashflowStmt,
    ExpExpr,
    ForEachDateStmt,
    IfStmt,
    IndexAtDateExpr,
    LetStmt,
    LocalRefExpr,
    LogExpr,
    MaxExpr,
    MinExpr,
    ParamRefExpr,
    PayoffModuleIR,
    RecordResultStmt,
    RequireStmt,
    ScheduleItemExpr,
    ScheduleSizeExpr,
    SetNpvStmt,
    SqrtExpr,
    UnaryExpr,
    WhereExpr,
)
from pythonore.payoff_ir.lower_ore import lower_ore_script
from pythonore.payoff_ir.lower_python import lower_python_payoff
from pythonore.payoff_ir.normalize import normalize_module
from pythonore.payoff_ir.validate import validate_module

__all__ = [
    "AbsExpr",
    "AboveProbExpr",
    "AssignStateStmt",
    "BelowProbExpr",
    "BlackScholesMonteCarloModel",
    "build_equity_ore_black_scholes_model",
    "BinaryExpr",
    "BooleanExpr",
    "CashflowValueExpr",
    "CompareExpr",
    "ConstantExpr",
    "ContinuationValueExpr",
    "DiscountFactorExpr",
    "EmitCashflowStmt",
    "EmitLoggedCashflowStmt",
    "ExpExpr",
    "ForEachDateStmt",
    "IfStmt",
    "IndexAtDateExpr",
    "LetStmt",
    "LocalRefExpr",
    "LogExpr",
    "MaxExpr",
    "MinExpr",
    "ParamRefExpr",
    "PayoffModuleIR",
    "RecordResultStmt",
    "RequireStmt",
    "ScheduleItemExpr",
    "ScheduleSizeExpr",
    "SetNpvStmt",
    "SqrtExpr",
    "UnaryExpr",
    "WhereExpr",
    "diff_modules",
    "emit_ore_script",
    "lower_ore_script",
    "lower_python_payoff",
    "normalize_module",
    "render_module",
    "validate_module",
]
