import os
from pathlib import Path

_PKG_DIR = Path(__file__).resolve().parent
_CACHE_ROOT = _PKG_DIR / ".cache"
_MPL_CACHE = _CACHE_ROOT / "matplotlib"
_FONTCONFIG_CACHE = _CACHE_ROOT / "fontconfig"
_MPL_CACHE.mkdir(parents=True, exist_ok=True)
_FONTCONFIG_CACHE.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("XDG_CACHE_HOME", str(_CACHE_ROOT))
os.environ.setdefault("MPLCONFIGDIR", str(_MPL_CACHE))
os.environ.setdefault("MPLBACKEND", "Agg")

from py_ore_tools.ore import OreBasic
from py_ore_tools.lgm import (
    LGM1F,
    LGMParams,
    ORE_PARITY_SEQUENCE_TYPE,
    OreMersenneTwisterGaussianRng,
    make_ore_gaussian_rng,
    simulate_ba_measure,
    simulate_lgm_measure,
)
from py_ore_tools.irs_xva_utils import (
    aggregate_exposure_profile_from_npv_paths,
    aggregate_portfolio_npv_paths,
    build_discount_curve_from_discount_pairs,
    build_discount_curve_from_zero_rate_pairs,
    build_irregular_exposure_grid,
    build_swap_schedules,
    apply_parallel_float_spread_shift_to_match_npv,
    calibrate_float_spreads_from_coupon,
    compute_portfolio_xva_from_trade_paths,
    compute_xva_from_exposure_profile,
    compute_xva_from_npv_paths,
    deflate_lgm_npv_paths,
    load_ore_default_curve_inputs,
    load_ore_discount_pairs_from_curves,
    load_ore_exposure_profile,
    load_ore_exposure_times,
    load_ore_legs_from_flows,
    load_swap_legs_from_portfolio,
    parse_lgm_params_from_calibration_xml,
    parse_lgm_params_from_simulation_xml,
    par_rate_from_trade,
    survival_probability_from_hazard,
    payer_swap_npv_at_time,
    swap_npv_from_ore_legs,
    swap_npv_from_ore_legs_dual_curve,
)
from py_ore_tools.lgm_fx_hybrid import LgmFxHybrid, MultiCcyLgmParams
from py_ore_tools.lgm_fx_xva_utils import (
    FxForwardDef,
    XccyFloatLegDef,
    aggregate_exposure_profile,
    build_lgm_params,
    build_two_ccy_hybrid,
    cva_terms_from_profile,
    fx_forward_npv,
    run_fx_forward_example,
    run_fx_forward_profile_xva,
    single_ccy_irs_npv,
    xccy_float_float_swap_npv,
)
from py_ore_tools.lgm_ir_options import (
    BermudanBackwardResult,
    BermudanExerciseDiagnostic,
    BermudanLsmcResult,
    BermudanSwaptionDef,
    CapFloorDef,
    bermudan_backward_price,
    bermudan_lsmc_result,
    bermudan_npv_paths,
    bermudan_price,
    capfloor_npv,
    capfloor_npv_paths,
    forward_rate_from_bonds,
)
from py_ore_tools.lgm_calibration import (
    BasketInstrument,
    CalibratedParameterBlock,
    CalibrationType,
    CurrencyLgmConfig,
    FallbackType,
    FloatSpreadMapping,
    LgmCalibrationConfig,
    LgmCalibrationError,
    LgmCalibrationPointResult,
    LgmCalibrationResult,
    LgmMarketInputs,
    ParamType,
    ParameterBlockConfig,
    ParameterTransformationConfig,
    QuantLibGsrCalibrationBackend,
    ReversionType,
    SwaptionSpec,
    VolatilityType,
    build_lgm_swaption_basket,
    calibrate_lgm_batch,
    calibrate_lgm_currency,
)
from py_ore_tools.rate_futures import (
    RateFutureModelParams,
    RateFutureQuote,
    future_convexity_adjustment,
    future_forward_rate,
    future_to_fra_rate,
    futures_price_to_rate,
)
from py_ore_tools.ore_snapshot import (
    CurveDFPayload,
    OreSnapshot,
    discount_factors_to_dataframe,
    dump_discount_factors_json,
    extract_discount_factors_by_currency,
    extract_market_instruments_by_currency,
    extract_market_instruments_by_currency_from_quotes,
    fit_discount_curves_from_ore_market,
    fit_discount_curves_from_programmatic_quotes,
    fitted_curves_to_dataframe,
    load_from_ore_xml,
    ore_input_validation_dataframe,
    quote_dicts_from_pairs,
    validate_ore_input_snapshot,
    validate_xva_snapshot_dataclasses,
    xva_snapshot_validation_dataframe,
)
from py_ore_tools.examples_regression import (
    DEFAULT_BASELINE_ROOT,
    DEFAULT_MANIFEST,
    ExampleRegressionCase,
    ExampleRegressionResult,
    compare_baselines,
    load_manifest,
    refresh_baselines,
)

__all__ = [
    "OreBasic",
    "LGMParams",
    "LGM1F",
    "ORE_PARITY_SEQUENCE_TYPE",
    "OreMersenneTwisterGaussianRng",
    "make_ore_gaussian_rng",
    "simulate_lgm_measure",
    "simulate_ba_measure",
    "build_discount_curve_from_discount_pairs",
    "build_discount_curve_from_zero_rate_pairs",
    "build_swap_schedules",
    "build_irregular_exposure_grid",
    "aggregate_exposure_profile_from_npv_paths",
    "aggregate_portfolio_npv_paths",
    "apply_parallel_float_spread_shift_to_match_npv",
    "calibrate_float_spreads_from_coupon",
    "compute_portfolio_xva_from_trade_paths",
    "compute_xva_from_exposure_profile",
    "compute_xva_from_npv_paths",
    "deflate_lgm_npv_paths",
    "load_ore_default_curve_inputs",
    "load_ore_discount_pairs_from_curves",
    "load_ore_exposure_profile",
    "load_ore_exposure_times",
    "load_ore_legs_from_flows",
    "load_swap_legs_from_portfolio",
    "parse_lgm_params_from_calibration_xml",
    "parse_lgm_params_from_simulation_xml",
    "survival_probability_from_hazard",
    "payer_swap_npv_at_time",
    "swap_npv_from_ore_legs",
    "swap_npv_from_ore_legs_dual_curve",
    "par_rate_from_trade",
    "MultiCcyLgmParams",
    "LgmFxHybrid",
    "FxForwardDef",
    "XccyFloatLegDef",
    "build_lgm_params",
    "build_two_ccy_hybrid",
    "fx_forward_npv",
    "run_fx_forward_example",
    "single_ccy_irs_npv",
    "xccy_float_float_swap_npv",
    "aggregate_exposure_profile",
    "cva_terms_from_profile",
    "run_fx_forward_profile_xva",
    "CapFloorDef",
    "BermudanBackwardResult",
    "BermudanExerciseDiagnostic",
    "BermudanLsmcResult",
    "BermudanSwaptionDef",
    "forward_rate_from_bonds",
    "capfloor_npv",
    "capfloor_npv_paths",
    "bermudan_backward_price",
    "bermudan_lsmc_result",
    "bermudan_npv_paths",
    "bermudan_price",
    "CalibrationType",
    "ParamType",
    "ReversionType",
    "VolatilityType",
    "FloatSpreadMapping",
    "FallbackType",
    "ParameterBlockConfig",
    "ParameterTransformationConfig",
    "SwaptionSpec",
    "CurrencyLgmConfig",
    "LgmCalibrationConfig",
    "LgmMarketInputs",
    "BasketInstrument",
    "CalibratedParameterBlock",
    "LgmCalibrationPointResult",
    "LgmCalibrationResult",
    "LgmCalibrationError",
    "QuantLibGsrCalibrationBackend",
    "build_lgm_swaption_basket",
    "calibrate_lgm_currency",
    "calibrate_lgm_batch",
    "RateFutureModelParams",
    "RateFutureQuote",
    "futures_price_to_rate",
    "future_convexity_adjustment",
    "future_forward_rate",
    "future_to_fra_rate",
    "CurveDFPayload",
    "OreSnapshot",
    "extract_discount_factors_by_currency",
    "discount_factors_to_dataframe",
    "dump_discount_factors_json",
    "extract_market_instruments_by_currency",
    "extract_market_instruments_by_currency_from_quotes",
    "fit_discount_curves_from_ore_market",
    "fit_discount_curves_from_programmatic_quotes",
    "fitted_curves_to_dataframe",
    "load_from_ore_xml",
    "validate_ore_input_snapshot",
    "ore_input_validation_dataframe",
    "validate_xva_snapshot_dataclasses",
    "xva_snapshot_validation_dataframe",
    "quote_dicts_from_pairs",
    "DEFAULT_BASELINE_ROOT",
    "DEFAULT_MANIFEST",
    "ExampleRegressionCase",
    "ExampleRegressionResult",
    "compare_baselines",
    "load_manifest",
    "refresh_baselines",
]
