from .dataclasses import (
    CollateralBalance,
    CollateralConfig,
    CreditEntityConfig,
    CreditSimulationConfig,
    ConventionsConfig,
    CounterpartyConfig,
    CrossAssetModelConfig,
    CreditCurve,
    CurveConfig,
    Curve,
    CurvePoint,
    EuropeanOption,
    FXForward,
    FXQuote,
    FXQuotes,
    FixingPoint,
    FixingsData,
    GenericProduct,
    IRS,
    MarketData,
    MarketQuote,
    NettingConfig,
    NettingSet,
    Portfolio,
    Product,
    PricingEngineConfig,
    RuntimeConfig,
    SimulationConfig,
    SimulationMarketConfig,
    SourceMeta,
    Trade,
    TodaysMarketConfig,
    XVAAnalyticConfig,
    XVAConfig,
    XVASnapshot,
)
from .exceptions import ConflictError, EngineRunError, InputCompatibilityError, MappingError, ValidationError
from .loader import XVALoader, merge_snapshots
from .mapper import MappedInputs, build_input_parameters, map_snapshot
from .parity import ParityCheckResult, ParityTolerance, compare_results
from .presets import stress_classic_native_preset, stress_classic_native_runtime
from .results import CubeAccessor, XVAResult
from .runtime import DeterministicToyAdapter, ORESwigAdapter, PythonLgmAdapter, XVAEngine, XVASession
from .stress_classic_templates import stress_classic_fixing_lines, stress_classic_market_lines, stress_classic_xml_buffers

# Backward-compatible aliases for prior prototype names.
MarketDataSnapshot = MarketData
PortfolioSnapshot = Portfolio

__all__ = [
    "CollateralBalance",
    "CollateralConfig",
    "CreditEntityConfig",
    "CreditSimulationConfig",
    "ConventionsConfig",
    "ConflictError",
    "CounterpartyConfig",
    "CrossAssetModelConfig",
    "CreditCurve",
    "CubeAccessor",
    "CurveConfig",
    "Curve",
    "CurvePoint",
    "DeterministicToyAdapter",
    "EngineRunError",
    "EuropeanOption",
    "FXForward",
    "FXQuote",
    "FXQuotes",
    "FixingPoint",
    "FixingsData",
    "GenericProduct",
    "InputCompatibilityError",
    "IRS",
    "MappedInputs",
    "MappingError",
    "MarketData",
    "MarketDataSnapshot",
    "MarketQuote",
    "NettingConfig",
    "NettingSet",
    "ORESwigAdapter",
    "PythonLgmAdapter",
    "ParityCheckResult",
    "ParityTolerance",
    "Portfolio",
    "PortfolioSnapshot",
    "PricingEngineConfig",
    "Product",
    "RuntimeConfig",
    "SimulationConfig",
    "SimulationMarketConfig",
    "SourceMeta",
    "TodaysMarketConfig",
    "Trade",
    "XVAAnalyticConfig",
    "ValidationError",
    "XVAConfig",
    "XVAEngine",
    "XVALoader",
    "XVAResult",
    "XVASession",
    "XVASnapshot",
    "build_input_parameters",
    "compare_results",
    "map_snapshot",
    "merge_snapshots",
    "stress_classic_native_preset",
    "stress_classic_native_runtime",
    "stress_classic_fixing_lines",
    "stress_classic_market_lines",
    "stress_classic_xml_buffers",
]
