from .dataclasses import (
    BermudanSwaption,
    CollateralBalance,
    CollateralConfig,
    CreditEntityConfig,
    CreditSimulationConfig,
    ConventionsConfig,
    CounterpartyConfig,
    CrossAssetModelConfig,
    CreditCurve,
    CurveConfig,
    Curve,
    CurvePoint,
    EuropeanOption,
    FXForward,
    FXQuote,
    FXQuotes,
    FixingPoint,
    FixingsData,
    GenericProduct,
    IRS,
    MarketData,
    MarketQuote,
    MporConfig,
    NettingConfig,
    NettingSet,
    Portfolio,
    Product,
    PricingEngineConfig,
    RuntimeConfig,
    SimulationConfig,
    SimulationMarketConfig,
    SourceMeta,
    Trade,
    TodaysMarketConfig,
    XVAAnalyticConfig,
    XVAConfig,
    XVASnapshot,
)
from .bermudan import (
    BermudanBenchmarkResult,
    BermudanPricingResult,
    BermudanPvSensitivity,
    BermudanSensitivityBenchmarkResult,
    BermudanSensitivityBenchmarkRow,
    benchmark_bermudan_from_ore_case,
    benchmark_bermudan_sensitivities_from_ore_case,
    price_bermudan_from_ore_case,
    price_bermudan_with_sensis_from_ore_case,
)
from .exceptions import ConflictError, EngineRunError, InputCompatibilityError, MappingError, ValidationError
from .dim import (
    PythonDeltaGammaVarHelper,
    PythonDimInput,
    PythonDynamicDeltaVarCalculator,
    PythonDynamicSimmCalculator,
    PythonSimpleDynamicSimm,
    PythonSimpleDynamicSimmConfig,
    PythonVarDimInput,
)
from .loader import XVALoader, merge_snapshots
from .mapper import MappedInputs, build_input_parameters, map_snapshot
from .parity import ParityCheckResult, ParityTolerance, compare_results
from .presets import stress_classic_native_preset, stress_classic_native_runtime
from .results import CubeAccessor, DIMMarginComponents, DIMResult, XVAResult
from .runtime import DeterministicToyAdapter, ORESwigAdapter, PythonLgmAdapter, XVAEngine, XVASession
from .sensitivity import (
    ORESensitivityEntry,
    OreSnapshotPythonLgmSensitivityComparator,
    PythonSensitivityEntry,
    SensitivityComparisonEntry,
)
from .stress_classic_templates import stress_classic_fixing_lines, stress_classic_market_lines, stress_classic_xml_buffers

# Backward-compatible aliases for prior prototype names.
MarketDataSnapshot = MarketData
PortfolioSnapshot = Portfolio

__all__ = [
    "CollateralBalance",
    "CollateralConfig",
    "BermudanBenchmarkResult",
    "BermudanPricingResult",
    "BermudanPvSensitivity",
    "BermudanSensitivityBenchmarkResult",
    "BermudanSensitivityBenchmarkRow",
    "BermudanSwaption",
    "CreditEntityConfig",
    "CreditSimulationConfig",
    "ConventionsConfig",
    "ConflictError",
    "CounterpartyConfig",
    "CrossAssetModelConfig",
    "CreditCurve",
    "CubeAccessor",
    "DIMMarginComponents",
    "DIMResult",
    "CurveConfig",
    "Curve",
    "CurvePoint",
    "DeterministicToyAdapter",
    "EngineRunError",
    "EuropeanOption",
    "FXForward",
    "FXQuote",
    "FXQuotes",
    "FixingPoint",
    "FixingsData",
    "GenericProduct",
    "InputCompatibilityError",
    "IRS",
    "MappedInputs",
    "MappingError",
    "MarketData",
    "MarketDataSnapshot",
    "MarketQuote",
    "MporConfig",
    "NettingConfig",
    "NettingSet",
    "ORESwigAdapter",
    "ORESensitivityEntry",
    "OreSnapshotPythonLgmSensitivityComparator",
    "PythonDimInput",
    "PythonDeltaGammaVarHelper",
    "PythonDynamicDeltaVarCalculator",
    "PythonDynamicSimmCalculator",
    "PythonLgmAdapter",
    "PythonSimpleDynamicSimm",
    "PythonSimpleDynamicSimmConfig",
    "PythonVarDimInput",
    "PythonSensitivityEntry",
    "ParityCheckResult",
    "ParityTolerance",
    "Portfolio",
    "PortfolioSnapshot",
    "PricingEngineConfig",
    "Product",
    "RuntimeConfig",
    "SimulationConfig",
    "SimulationMarketConfig",
    "SourceMeta",
    "SensitivityComparisonEntry",
    "TodaysMarketConfig",
    "Trade",
    "XVAAnalyticConfig",
    "ValidationError",
    "XVAConfig",
    "XVAEngine",
    "XVALoader",
    "XVAResult",
    "XVASession",
    "XVASnapshot",
    "benchmark_bermudan_from_ore_case",
    "benchmark_bermudan_sensitivities_from_ore_case",
    "build_input_parameters",
    "compare_results",
    "map_snapshot",
    "merge_snapshots",
    "price_bermudan_from_ore_case",
    "price_bermudan_with_sensis_from_ore_case",
    "stress_classic_native_preset",
    "stress_classic_native_runtime",
    "stress_classic_fixing_lines",
    "stress_classic_market_lines",
    "stress_classic_xml_buffers",
]
